# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Anmol Vijayvargiya
paginate:       5
baseurl:        ""
url:            "http://anmolvj.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Anmol Vijayvargiya
  url:          http://anmolvj.com
  email:        avijayvargiya@scu.edu

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
